# required_tags is a list of tags that must be present on the host
# for it to be considered for DNS registration. Optional.
required_tags = ["publish:yes"]
# required_suffix will only register hosts with this domain (must match the
# full domain suffix.) Optional.
required_suffix = ""
# trim_suffix will remove the domain from the hostname (e.g. host.example.com
# will become host)
trim_suffix = true
# append_suffix will append the domain to the hostname (e.g. host will become
# host.example.com.) This step occurs after trim_suffix, so you can convert
# host.example.com to host.nebula.example.com, for example.
append_suffix = "nebula.example.com"
# prune_records will remove any records in the DNS zone that do not correspond
# to a host in the Nebula network.
prune_records = true

[cloudflare]
# api_token is the Cloudflare API token. It needs the `Zone:DNS:Edit`
# permission for the zone specified in zone_name.
api_token = ""
# zone_name is the DNS zone (domain) to create records in (e.g. example.com)
zone_name = ""

[definednet]
# api_token is the Defined.net API token. It needs the `hosts:list` permission.
api_token = ""
