name: Build and test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build binary
        run: make bin

      - name: Run tests
        run: make testv
